### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yangxiannfyxh** [swaggo/gin-swagger#91]
**Describe the bug**
panic: runtime error: invalid memory address or nil pointer dereference when I use `swag init --parseDependency`

**To Reproduce**
```
export GO111MODULE=on
swag init --parseDependency
```
```
2019/11/22 12:04:01 Generate swagger docs....
2019/11/22 12:04:01 Generate general API Info, search dir:./
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x843d12]

goroutine 1 [running]:
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc0002bce00, 0xc0005bda30, 0x0, 0x0)
	/root/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:1323 +0x62
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc0002bce00, 0xc00098f980, 0x46, 0x0)
	/root/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:1341 +0x13e
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc0002bce00, 0xc0007529a0, 0x0, 0x0)
	/root/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:1341 +0x13e
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc0002bce00, 0xc0007bb238, 0x0, 0x0)
	/root/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:1341 +0x13e
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc0002bce00, 0xc0005a9390, 0x0, 0x0)
	/root/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:1341 +0x13e
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc0002bce00, 0xc0007cd658, 0x0, 0x0)
	/root/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:1341 +0x13e
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc0002bce00, 0xc0009594f8, 0x0, 0x0)
	/root/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:1341 +0x13e
github.com/swaggo/swag.(*Parser).getAllGoFileInfoFromDeps(0xc0002bce00, 0xc000919130, 0x0, 0x0)
	/root/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:1341 +0x13e
github.com/swaggo/swag.(*Parser).ParseAPI(0xc0002bce00, 0x9a2ee1, 0x2, 0x9a60f9, 0x7, 0x0, 0xc0003314d0)
	/root/pkg/mod/github.com/swaggo/swag@v1.6.3/parser.go:130 +0x44c
github.com/swaggo/swag/gen.(*Gen).Build(0xc008e595de, 0xc008e59640, 0x0, 0x0)
	/root/pkg/mod/github.com/swaggo/swag@v1.6.3/gen/gen.go:66 +0x2c4
main.main.func1(0xc00022e2c0, 0x0, 0xc00011e310)
	/root/pkg/mod/github.com/swaggo/swag@v1.6.3/cmd/swag/main.go:45 +0x2ea
github.com/urfave/cli.HandleAction(0x8fc7a0, 0x9c7fc0, 0xc00022e2c0, 0xc00022e2c0, 0x0)
	/root/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:523 +0xbe
github.com/urfave/cli.Command.Run(0x9a386f, 0x4, 0x0, 0x0, 0xc0002ed5b0, 0x1, 0x1, 0x9a9ff1, 0xe, 0x0, ...)
	/root/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:174 +0x521
github.com/urfave/cli.(*App).Run(0xc0000941c0, 0xc000088150, 0x3, 0x3, 0x0, 0x0)
	/root/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:276 +0x729
main.main()
	/root/pkg/mod/github.com/swaggo/swag@v1.6.3/cmd/swag/main.go:93 +0x65d
```

**The annotation are as follows**
```
import "k8s.io/api/core/v1"
// @Success 200 {object} v1.ConfigMap
```

**Your swag version**
swag version v1.6.3

**Your go version**
go version go1.12.7 linux/amd64

**Comment by ubogdan** [comment]
This has nothing to do with the middleware. Please open the issue on [swag](https://github.com/swaggo/swag/issues).
